name: Release
on:
  pull_request:

jobs:
  release_to_npm:
    name: Release to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: 'packages/**/package-lock.json'
      - run: npm deprecate react-jsonschema-form "react-jsonschema-form has been moved to @rjsf/core"
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npx lerna publish from-package --yes
      - if: always()
        run: rm .npmrc
